/* SAMPLE COLLECTORS */
export const GET_TEST_CERTIFICATES = "GET_TEST_CERTIFICATES";
export const GET_TEST_CERTIFICATES_SUCCESS = "GET_TEST_CERTIFICATES_SUCCESS";
export const GET_TEST_CERTIFICATES_FAIL = "GET_TEST_CERTIFICATES_FAIL";

export const ADD_NEW_TEST_CERTIFICATE = "ADD_NEW_TEST_CERTIFICATE";
export const ADD_TEST_CERTIFICATE_SUCCESS = "ADD_TEST_CERTIFICATE_SUCCESS";
export const ADD_TEST_CERTIFICATE_FAIL = "ADD_TEST_CERTIFICATE_FAIL";

export const UPDATE_TEST_CERTIFICATE = "UPDATE_TEST_CERTIFICATE";
export const UPDATE_TEST_CERTIFICATE_SUCCESS =
  "UPDATE_TEST_CERTIFICATE_SUCCESS";
export const UPDATE_TEST_CERTIFICATE_FAIL = "UPDATE_TEST_CERTIFICATE_FAIL";

export const DELETE_TEST_CERTIFICATE = "DELETE_TEST_CERTIFICATE";
export const DELETE_TEST_CERTIFICATE_SUCCESS =
  "DELETE_TEST_CERTIFICATE_SUCCESS";
export const DELETE_TEST_CERTIFICATE_FAIL = "DELETE_TEST_CERTIFICATE_FAIL";
