/* PRODUCTS */
export const GET_NEARBY_PROFILES = "GET_NEARBY_PROFILES";
export const GET_NEARBY_PROFILES_SUCCESS = "GET_NEARBY_PROFILES_SUCCESS";
export const GET_NEARBY_PROFILES_FAIL = "GET_NEARBY_PROFILES_FAIL";
