/* SAMPLE COLLECTORS */
// get METHODS
export const GET_METHODS_LIST = "GET_METHODS_LIST";
export const GET_METHODS_LIST_SUCCESS ="GET_METHODS_LIST_SUCCESS";
export const GET_METHODS_LIST_FAIL = "GET_METHODS_LIST_FAIL";
// Add METHODS
export const ADD_NEW_METHODS = "ADD_NEW_METHODS";
export const ADD_NEW_METHODS_SUCCESS = "ADD_NEW_METHODS_SUCCESS";
export const ADD_NEW_METHODS_FAIL = "ADD_NEW_METHODS_FAIL";
//Update METHODS
export const UPDATE_METHODS = "UPDATE_METHODS";
export const UPDATE_METHODS_SUCCESS = "UPDATE_METHODS_SUCCESS";
export const UPDATE_METHODS_FAIL = "UPDATE_METHODS_FAIL";
