/*  PATIENT TEST APPOINTMENTtS */

export const GET_PATIENTS_LIST =
  "GET_PATIENTS_LIST";
export const GET_PATIENTS_LIST_SUCCESS =
  "GET_PATIENTS_LIST_SUCCESS";
export const GET_PATIENTS_LIST_FAIL =
  "GET_PATIENTS_LIST_FAIL";
