/*  PATIENT TEST APPOINTMENTtS */

export const GET_DONOR_REFERRED_APPOINTMENTS_LIST =
  "GET_DONOR_REFERRED_APPOINTMENTS_LIST";
export const GET_DONOR_REFERRED_APPOINTMENTS_LIST_SUCCESS =
  "GET_DONOR_REFERRED_APPOINTMENTS_LIST_SUCCESS";
export const GET_DONOR_REFERRED_APPOINTMENTS_LIST_FAIL =
  "GET_DONOR_REFERRED_APPOINTMENTS_LIST_FAIL";
