/*  PATIENT TEST APPOINTMENTtS */

export const GET_B2B_ALL_CLIENTS_LIST =
  "GET_B2B_ALL_CLIENTS_LIST";
export const GET_B2B_ALL_CLIENTS_LIST_SUCCESS =
  "GET_B2B_ALL_CLIENTS_LIST_SUCCESS";
export const GET_B2B_ALL_CLIENTS_LIST_FAIL =
  "GET_B2B_ALL_CLIENTS_LIST_FAIL";
