/* SAMPLE COLLECTORS */
export const GET_ADVERTISEMENT_PRICE_LISTS = "GET_ADVERTISEMENT_PRICE_LISTS";
export const GET_ADVERTISEMENT_PRICE_LISTS_SUCCESS =
  "GET_ADVERTISEMENT_PRICE_LISTS_SUCCESS";
export const GET_ADVERTISEMENT_PRICE_LISTS_FAIL = "GET_ADVERTISEMENT_PRICE_LISTS_FAIL";

export const ADD_NEW_ADVERTISEMENT_PRICE_LIST = "ADD_NEW_ADVERTISEMENT_PRICE_LIST";
export const ADD_ADVERTISEMENT_PRICE_LIST_SUCCESS =
  "ADD_ADVERTISEMENT_PRICE_LIST_SUCCESS";
export const ADD_ADVERTISEMENT_PRICE_LIST_FAIL = "ADD_ADVERTISEMENT_PRICE_LIST_FAIL";

export const UPDATE_ADVERTISEMENT_PRICE_LIST = "UPDATE_ADVERTISEMENT_PRICE_LIST";
export const UPDATE_ADVERTISEMENT_PRICE_LIST_SUCCESS =
  "UPDATE_ADVERTISEMENT_PRICE_LIST_SUCCESS";
export const UPDATE_ADVERTISEMENT_PRICE_LIST_FAIL =
  "UPDATE_ADVERTISEMENT_PRICE_LIST_FAIL";

export const DELETE_ADVERTISEMENT_PRICE_LIST = "DELETE_ADVERTISEMENT_PRICE_LIST";
export const DELETE_ADVERTISEMENT_PRICE_LIST_SUCCESS =
  "DELETE_ADVERTISEMENT_PRICE_LIST_SUCCESS";
export const DELETE_ADVERTISEMENT_PRICE_LIST_FAIL =
  "DELETE_ADVERTISEMENT_PRICE_LIST_FAIL";
