export const GET_PENDING_AUDITS = "GET_PENDING_AUDITS";
export const GET_PENDING_AUDITS_SUCCESS = "GET_PENDING_AUDITS_SUCCESS";
export const GET_PENDING_AUDITS_FAIL = "GET_PENDING_AUDITS_FAIL";

export const GET_INPROCESS_AUDITS = "GET_INPROCESS_AUDITS";
export const GET_INPROCESS_AUDITS_SUCCESS = "GET_INPROCESS_AUDITS_SUCCESS";
export const GET_INPROCESS_AUDITS_FAIL = "GET_INPROCESS_AUDITS_FAIL";

export const GET_PASSED_AUDITS = "GET_PASSED_AUDITS";
export const GET_PASSED_AUDITS_SUCCESS = "GET_PASSED_AUDITS_SUCCESS";
export const GET_PASSED_AUDITS_FAIL = "GET_PASSED_AUDITS_FAIL";

export const GET_FAILED_AUDITS = "GET_FAILED_AUDITS";
export const GET_FAILED_AUDITS_SUCCESS = "GET_FAILED_AUDITS_SUCCESS";
export const GET_FAILED_AUDITS_FAIL = "GET_FAILED_AUDITS_FAIL";

export const ASSIGN_AUDIT = "ASSIGN_AUDIT";
export const ASSIGN_AUDIT_SUCCESS = "ASSIGN_AUDIT_SUCCESS";
export const ASSIGN_AUDIT_FAIL = "ASSIGN_AUDIT_FAIL";
