/*  PATIENT TEST APPOINTMENTtS */
export const GET_PATIENT_TEST_APPOINTMENTS_LIST =
  "GET_PATIENT_TEST_APPOINTMENTS_LIST";
export const GET_PATIENT_TEST_APPOINTMENTS_LIST_SUCCESS =
  "GET_PATIENT_TEST_APPOINTMENTS_LIST_SUCCESS";
export const GET_PATIENT_TEST_APPOINTMENTS_LIST_FAIL =
  "GET_PATIENT_TEST_APPOINTMENTS_LIST_FAIL";
