/* SAMPLE COLLECTORS */
export const GET_ADVERTISEMENTS = "GET_ADVERTISEMENTS";
export const GET_ADVERTISEMENTS_SUCCESS =
  "GET_ADVERTISEMENTS_SUCCESS";
export const GET_ADVERTISEMENTS_FAIL = "GET_ADVERTISEMENTS_FAIL";

export const ADD_NEW_ADVERTISEMENT = "ADD_NEW_ADVERTISEMENT";
export const ADD_ADVERTISEMENT_SUCCESS =
  "ADD_ADVERTISEMENT_SUCCESS";
export const ADD_ADVERTISEMENT_FAIL = "ADD_ADVERTISEMENT_FAIL";

export const UPDATE_ADVERTISEMENT = "UPDATE_ADVERTISEMENT";
export const UPDATE_ADVERTISEMENT_SUCCESS =
  "UPDATE_ADVERTISEMENT_SUCCESS";
export const UPDATE_ADVERTISEMENT_FAIL =
  "UPDATE_ADVERTISEMENT_FAIL";

export const DELETE_ADVERTISEMENT = "DELETE_ADVERTISEMENT";
export const DELETE_ADVERTISEMENT_SUCCESS =
  "DELETE_ADVERTISEMENT_SUCCESS";
export const DELETE_ADVERTISEMENT_FAIL =
  "DELETE_ADVERTISEMENT_FAIL";
