/* INSTRUMENT List */
export const GET_INSTRUMENT_LIST = "GET_INSTRUMENT_LIST";
export const GET_INSTRUMENT_LIST_SUCCESS =
  "GET_INSTRUMENT_LIST_SUCCESS";
export const GET_INSTRUMENT_LIST_FAIL = "GET_INSTRUMENT_LIST_FAIL";

///adding new instrument
export const ADD_NEW_INSTRUMENT = "ADD_NEW_INSTRUMENT";
export const ADD_NEW_INSTRUMENT_SUCCESS = "ADD_NEW_INSTRUMENT_SUCCESS";
export const ADD_NEW_INSTRUMENT_FAIL = "ADD_NEW_INSTRUMENT_FAIL";

//update INSTRUMENT
export const UPDATE_INSTRUMENT = "UPDATE_INSTRUMENT";
export const UPDATE_INSTRUMENT_SUCCESS = "UPDATE_INSTRUMENT_SUCCESS";
export const UPDATE_INSTRUMENT_FAIL = "UPDATE_INSTRUMENT_FAIL";