
export const GET_CSR_APPOINTMENTS = "GET_CSR_APPOINTMENTS";
export const GET_CSR_APPOINTMENTS_SUCCESS = "GET_CSR_APPOINTMENTS_SUCCESS";
export const GET_CSR_APPOINTMENTS_FAIL = "GET_CSR_APPOINTMENTS_FAIL";

export const UPDATE_CSR_APPOINTMENTS = "UPDATE_CSR_APPOINTMENTS";
export const UPDATE_CSR_APPOINTMENTS_SUCCESS =
  "UPDATE_CSR_APPOINTMENTS_SUCCESS";
export const UPDATE_CSR_APPOINTMENTS_FAIL = "UPDATE_CSR_APPOINTMENTS_FAIL";