/* SAMPLE COLLECTORS */
// get units
export const GET_PARTICIPANT_LIST = "GET_PARTICIPANT_LIST";
export const GET_PARTICIPANT_LIST_SUCCESS ="GET_PARTICIPANT_LIST_SUCCESS";
export const GET_PARTICIPANT_LIST_FAIL = "GET_PARTICIPANT_LIST_FAIL";
