/* TESTS AVAILABLE */
export const GET_TESTS = "GET_TESTS";
export const GET_TESTS_SUCCESS = "GET_TESTS_SUCCESS";
export const GET_TESTS_FAIL = "GET_TESTS_FAIL";

/* UNITS LIST */
export const GET_UNITS = "GET_UNITS";
export const GET_UNITS_SUCCESS = "GET_UNITS_SUCCESS";
export const GET_UNITS_FAIL = "GET_UNITS_FAIL";

/* OFFERED TESTS */
export const GET_OFFERED_TESTS = "GET_OFFERED_TESTS";
export const GET_OFFERED_TESTS_SUCCESS = "GET_OFFERED_TESTS_SUCCESS";
export const GET_OFFERED_TESTS_FAIL = "GET_OFFERED_TESTS_FAIL";

export const GET_OFFEREDTEST_REFERRELFEE = "GET_OFFEREDTEST_REFERRELFEE";
export const GET_OFFEREDTEST_REFERRELFEE_SUCCESS = "GET_OFFEREDTEST_REFERRELFEE_SUCCESS";
export const GET_OFFEREDTEST_REFERRELFEE_FAIL = "GET_OFFEREDTEST_REFERRELFEE_FAIL";

export const ADD_NEW_OFFERED_TEST = "ADD_NEW_OFFERED_TEST";
export const ADD_OFFERED_TEST_SUCCESS = "ADD_OFFERED_TEST_SUCCESS";
export const ADD_OFFERED_TEST_FAIL = "ADD_OFFERED_TEST_FAIL";

export const UPDATE_OFFERED_TEST = "UPDATE_OFFERED_TEST";
export const UPDATE_OFFERED_TEST_SUCCESS = "UPDATE_OFFERED_TEST_SUCCESS";
export const UPDATE_OFFERED_TEST_FAIL = "UPDATE_OFFERED_TEST_FAIL";

export const DELETE_OFFERED_TEST = "DELETE_OFFERED_TEST";
export const DELETE_OFFERED_TEST_SUCCESS = "DELETE_OFFERED_TEST_SUCCESS";
export const DELETE_OFFERED_TEST_FAIL = "DELETE_OFFERED_TEST_FAIL";
