/* ADVERTISEMENET INVOICES */
export const GET_ADV_INVOICE_DETAIL = "GET_ADV_INVOICE_DETAIL";
export const GET_ADV_INVOICE_DETAIL_SUCCESS = "GET_ADV_INVOICE_DETAIL_SUCCESS";
export const GET_ADV_INVOICE_DETAIL_FAIL = "GET_ADV_INVOICE_DETAIL_FAIL";
