/* PRODUCTS */
export const GET_NEARBY_PACKAGES = "GET_NEARBY_PACKAGES";
export const GET_NEARBY_PACKAGES_SUCCESS = "GET_NEARBY_PACKAGES_SUCCESS";
export const GET_NEARBY_PACKAGES_FAIL = "GET_NEARBY_PACKAGES_FAIL";

export const GET_PACKAGES = "GET_PACKAGES";
export const GET_PACKAGES_SUCCESS = "GET_PACKAGES_SUCCESS";
export const GET_PACKAGES_FAIL = "GET_PACKAGES_FAIL";

export const GET_TERRITORIES_LIST =
  "GET_TERRITORIES_LIST";
export const GET_TERRITORIES_LIST_SUCCESS =
  "GET_TERRITORIES_LIST_SUCCESS";
export const GET_TERRITORIES_LIST_FAIL =
  "GET_TERRITORIES_LIST_FAIL";