/* SAMPLE COLLECTORS */
export const GET_NEARBY_LABS = "GET_NEARBY_LABS";
export const GET_NEARBY_LABS_SUCCESS = "GET_NEARBY_LABS_SUCCESS";
export const GET_NEARBY_LABS_FAIL = "GET_NEARBY_LABS_FAIL";

