/* SAMPLE COLLECTORS */
export const GET_LABCORPORATE = "GET_LABCORPORATE";
export const GET_LABCORPORATE_SUCCESS = "GET_LABCORPORATE_SUCCESS";
export const GET_LABCORPORATE_FAIL = "GET_LABCORPORATE_FAIL";

export const ADD_NEW_CEMPLOYEE_DATA = "ADD_NEW_CEMPLOYEE_DATA";
export const ADD_CEMPLOYEE_DATA_SUCCESS =
  "ADD_CEMPLOYEE_DATA_SUCCESS";
export const ADD_CEMPLOYEE_DATA_FAIL = "ADD_CEMPLOYEE_DATA_FAIL";


export const UPDATE_CEMPLOYEE = "UPDATE_CEMPLOYEE";
export const UPDATE_CEMPLOYEE_SUCCESS =
  "UPDATE_CEMPLOYEE_SUCCESS";
export const UPDATE_CEMPLOYEE_FAIL =
  "UPDATE_CEMPLOYEE_FAIL";

export const GET_CEMPLOYEES = "get_cemployees";
export const GET_CEMPLOYEES_SUCCESS = "get_cemployees_success";
export const GET_CEMPLOYEES_FAIL = "get_cemployees_fail";