/* PATHOLOGISTS */
export const GET_ACTIVITY_LOG = "GET_ACTIVITY_LOG";
export const GET_ACTIVITY_LOG_SUCCESS = "GET_ACTIVITY_LOG_SUCCESS";
export const GET_ACTIVITY_LOG_FAIL = "GET_ACTIVITY_LOG_FAIL";

export const GET_CSR_OFFICER_NOTIFICATION = "GET_CSR_OFFICER_NOTIFICATION";
export const GET_CSR_OFFICER_NOTIFICATION_SUCCESS = "GET_CSR_OFFICER_NOTIFICATION_SUCCESS";
export const GET_CSR_OFFICER_NOTIFICATION_FAIL = "GET_CSR_OFFICER_NOTIFICATION_FAIL";