/* LAB PROFILE */
export const GET_SAMPLE_COLLECTOR_PROFILE = "GET_SAMPLE_COLLECTOR_PROFILE";
export const GET_SAMPLE_COLLECTOR_PROFILE_SUCCESS = "GET_SAMPLE_COLLECTOR_PROFILE_SUCCESS";
export const GET_SAMPLE_COLLECTOR_PROFILE_FAIL = "GET_SAMPLE_COLLECTOR_PROFILE_FAIL";

export const UPDATE_SAMPLE_COLLECTOR_PROFILE = "UPDATE_SAMPLE_COLLECTOR_PROFILE";
export const UPDATE_SAMPLE_COLLECTOR_PROFILE_SUCCESS = "UPDATE_SAMPLE_COLLECTOR_PROFILE_SUCCESS";
export const UPDATE_SAMPLE_COLLECTOR_PROFILE_FAIL = "UPDATE_SAMPLE_COLLECTOR_PROFILE_FAIL";
