/*  PATIENT TEST APPOINTMENTtS */

export const GET_B2B_REFERRED_PATIENTS_LIST =
  "GET_B2B_REFERRED_PATIENTS_LIST";
export const GET_B2B_REFERRED_PATIENTS_LIST_SUCCESS =
  "GET_B2B_REFERRED_PATIENTS_LIST_SUCCESS";
export const GET_B2B_REFERRED_PATIENTS_LIST_FAIL =
  "GET_B2B_REFERRED_PATIENTS_LIST_FAIL";
