/* SAMPLE COLLECTORS */
// get units
export const GET_UNITS_LIST = "GET_UNITS_LIST";
export const GET_UNITS_LIST_SUCCESS ="GET_UNITS_LIST_SUCCESS";
export const GET_UNITS_LIST_FAIL = "GET_UNITS_LIST_FAIL";
// Add units
export const ADD_NEW_UNITS = "ADD_NEW_UNITS";
export const ADD_NEW_UNITS_SUCCESS = "ADD_NEW_UNITS_SUCCESS";
export const ADD_NEW_UNITS_FAIL = "ADD_NEW_UNITS_FAIL";
//Update Units
export const UPDATE_UNITS = "UPDATE_UNITS";
export const UPDATE_UNITS_SUCCESS = "UPDATE_UNITS_SUCCESS";
export const UPDATE_UNITS_FAIL = "UPDATE_UNITS_FAIL";
