/* SAMPLE COLLECTORS */
// get units
export const GET_UNITS_LIST = "GET_UNITS_LIST";
export const GET_UNITS_LIST_SUCCESS ="GET_UNITS_LIST_SUCCESS";
export const GET_UNITS_LIST_FAIL = "GET_UNITS_LIST_FAIL";
// Add units
export const ADD_NEW_UNITS = "ADD_NEW_UNITS";
export const ADD_NEW_UNITS_SUCCESS = "ADD_NEW_UNITS_SUCCESS";
export const ADD_NEW_UNITS_FAIL = "ADD_NEW_UNITS_FAIL";
//Update Units
export const UPDATE_UNITS = "UPDATE_UNITS";
export const UPDATE_UNITS_SUCCESS = "UPDATE_UNITS_SUCCESS";
export const UPDATE_UNITS_FAIL = "UPDATE_UNITS_FAIL";


/////UNITS added by analytes

export const GET_ANALYTESUNITS_LIST = "GET_ANALYTESUNITS_LIST_LIST";
export const GET_ANALYTESUNITS_LIST_SUCCESS ="GET_ANALYTESUNITS_LIST_SUCCESS";
export const GET_ANALYTESUNITS_LIST_FAIL = "GET_ANALYTESUNITS_LIST_FAIL";
// Add units
export const ADD_NEW_ANALYTESUNITS = "ADD_NEW_ANALYTESUNITS";
export const ADD_NEW_ANALYTESUNITS_SUCCESS = "ADD_NEW_ANALYTESUNITS_SUCCESS";
export const ADD_NEW_ANALYTESUNITS_FAIL = "ADD_NEW_ANALYTESUNITS_FAIL";
//Update Units
export const UPDATE_ANALYTESUNITS = "UPDATE_ANALYTESUNITS";
export const UPDATE_ANALYTESUNITS_SUCCESS = "UPDATE_ANALYTESUNITS_SUCCESS";
export const UPDATE_ANALYTESUNITS_FAIL = "UPDATE_ANALYTESUNITS_FAIL";


///get analytes associated with unit
export const GET_ANALYTESUNITS = "GET_ANALYTESUNITS_LIST";
export const GET_ANALYTESUNITS_SUCCESS ="GET_ANALYTESUNITS_SUCCESS";
export const GET_ANALYTESUNITS_FAIL = "GET_ANALYTESUNITS_FAIL";