export const GET_LABS_MOF = "GET_LABS_MOF";
export const GET_LABS_MOF_SUCCESS = "GET_LABS_MOF_success";
export const GET_LABS_MOF_FAIL = "GET_LABS_MOF_fail";

export const GET_BANKS = "get_banks";
export const GET_BANKS_SUCCESS = "get_banks_success";
export const GET_BANKS_FAIL = "get_banks_fail";

export const GET_OUT_PAYMENT =
  "GET_OUT_PAYMENT";
export const GET_OUT_PAYMENT_SUCCESS =
  "GET_OUT_PAYMENT_SUCCESS";
export const GET_OUT_PAYMENT_FAIL =
  "GET_OUT_PAYMENT_FAIL";

export const ADD_NEW_OUT_PAYMENT = "ADD_NEW_OUT_PAYMENT";
export const ADD_OUT_PAYMENT_SUCCESS =
  "ADD_OUT_PAYMENT_SUCCESS";
export const ADD_OUT_PAYMENT_FAIL = "ADD_OUT_PAYMENT_FAIL";

export const GET_BANK_ACCOUNTS = "GET_BANK_ACCOUNTS";
export const GET_BANK_ACCOUNTS_SUCCESS =
  "GET_BANK_ACCOUNTS_SUCCESS";
export const GET_BANK_ACCOUNTS_FAIL = "GET_BANK_ACCOUNTS_FAIL";

export const GET_B2B_CLIENTS =
  "GET_B2B_CLIENTS";
export const GET_B2B_CLIENTS_SUCCESS =
  "GET_B2B_CLIENTS_SUCCESS";
export const GET_B2B_CLIENTS_FAIL =
  "GET_B2B_CLIENTS_FAIL";