/* Instrument types */
export const GET_INSTRUMENT_TYPE_LIST = "GET_INSTRUMENT_TYPE_LIST";
export const GET_INSTRUMENT_TYPE_LIST_SUCCESS = "GET_INSTRUMENT_TYPE_LIST_SUCCESS";
export const GET_INSTRUMENT_TYPE_LIST_FAIL = "GET_INSTRUMENT_TYPE_LIST_FAIL";


///adding new instrument type
export const ADD_NEW_INSTRUMENT_TYPE = "ADD_NEW_INSTRUMENT_TYPE";
export const ADD_NEW_INSTRUMENT_TYPE_SUCCESS = "ADD_NEW_INSTRUMENT_TYPE_SUCCESS";
export const ADD_NEW_INSTRUMENT_TYPE_FAIL = "ADD_NEW_INSTRUMENT_TYPE_FAIL";

//update instrument type
export const UPDATE_NEW_INSTRUMENT_TYPE = "UPDATE_NEW_INSTRUMENT_TYPE";
export const UPDATE_NEW_INSTRUMENT_TYPE_SUCCESS = "UPDATE_NEW_INSTRUMENT_TYPE_SUCCESS";
export const UPDATE_NEW_INSTRUMENT_TYPE_FAIL = "UPDATE_NEW_INSTRUMENT_TYPE_FAIL";


/* Analyte List */
export const GET_ANALYTE_LIST = "GET_ANALYTE_LIST";
export const GET_ANALYTE_LIST_SUCCESS = "GET_ANALYTE_LIST_SUCCESS";
export const GET_ANALYTE_LIST_FAIL = "GET_ANALYTE_LIST_FAIL";


///adding new Analyte
export const ADD_NEW_ANALYTE_LIST = "ADD_NEW_ANALYTE_LIST";
export const ADD_NEW_ANALYTE_LIST_SUCCESS = "ADD_NEW_ANALYTE_LIST_SUCCESS";
export const ADD_NEW_ANALYTE_LIST_FAIL = "ADD_NEW_ANALYTE_LIST_FAIL";

//update Analyte
export const UPDATE_NEW_ANALYTE_LIST = "UPDATE_NEW_ANALYTE_LIST";
export const UPDATE_NEW_ANALYTE_LIST_SUCCESS = "UPDATE_NEW_ANALYTE_LIST_SUCCESS";
export const UPDATE_NEW_ANALYTE_LIST_FAIL = "UPDATE_NEW_ANALYTE_LIST_FAIL";




///// Get Analytes added by Cycle page

export const GET_CYCLEANALYTE_LIST = "GET_CYCLEANALYTE_LIST_LIST";
export const GET_CYCLEANALYTE_LIST_SUCCESS ="GET_CYCLEANALYTE_LIST_SUCCESS";
export const GET_CYCLEANALYTE_LIST_FAIL = "GET_CYCLEANALYTE_LIST_FAIL";
// Add Analytes added by Cycle page
export const ADD_NEW_CYCLEANALYTE = "ADD_NEW_CYCLEANALYTE";
export const ADD_NEW_CYCLEANALYTE_SUCCESS = "ADD_NEW_CYCLEANALYTE_SUCCESS";
export const ADD_NEW_CYCLEANALYTE_FAIL = "ADD_NEW_CYCLEANALYTE_FAIL";
//Update Analytes added by Cycle page
export const UPDATE_CYCLEANALYTE = "UPDATE_CYCLEANALYTE";
export const UPDATE_CYCLEANALYTE_SUCCESS = "UPDATE_CYCLEANALYTE_SUCCESS";
export const UPDATE_CYCLEANALYTE_FAIL = "UPDATE_CYCLEANALYTE_FAIL";