/* PRODUCTS */
export const GET_NEARBY_LABS = "GET_NEARBY_LABS";
export const GET_NEARBY_LABS_SUCCESS = "GET_NEARBY_LABS_SUCCESS";
export const GET_NEARBY_LABS_FAIL = "GET_NEARBY_LABS_FAIL";

/* PRODUCT DETAILS */
export const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL";
export const GET_PRODUCT_DETAIL_SUCCESS = "GET_PRODUCT_DETAIL_SUCCESS";
export const GET_PRODUCT_DETAIL_FAIL = "GET_PRODUCT_DETAIL_FAIL";
