/* TEST APPOINTMENTtS */
export const GET_TEST_APPOINTMENTS_PENDING_LIST = "GET_TEST_APPOINTMENTS_PENDING_LIST";
export const GET_TEST_APPOINTMENTS_PENDING_LIST_SUCCESS =
  "GET_TEST_APPOINTMENTS_PENDING_LIST_SUCCESS";
export const GET_TEST_APPOINTMENTS_PENDING_LIST_FAIL = "GET_TEST_APPOINTMENTS_PENDING_LIST_FAIL";

export const GET_TEST_APPOINTMENTS_IN_PROCESS_LIST = "GET_TEST_APPOINTMENTS_IN_PROCESS_LIST";
export const GET_TEST_APPOINTMENTS_IN_PROCESS_LIST_SUCCESS =
  "GET_TEST_APPOINTMENTS_IN_PROCESS_LIST_SUCCESS";
export const GET_TEST_APPOINTMENTS_IN_PROCESS_LIST_FAIL = "GET_TEST_APPOINTMENTS_IN_PROCESS_LIST_FAIL";

export const GET_TEST_APPOINTMENTS_COMPLETED_LIST = "GET_TEST_APPOINTMENTS_COMPLETED_LIST";
export const GET_TEST_APPOINTMENTS_COMPLETED_LIST_SUCCESS =
  "GET_TEST_APPOINTMENTS_COMPLETED_LIST_SUCCESS";
export const GET_TEST_APPOINTMENTS_COMPLETED_LIST_FAIL = "GET_TEST_APPOINTMENTS_COMPLETED_LIST_FAIL";

export const UPDATE_TEST_APPOINTMENT = "UPDATE_TEST_APPOINTMENT";
export const UPDATE_TEST_APPOINTMENT_SUCCESS =
  "UPDATE_TEST_APPOINTMENT_SUCCESS";
export const UPDATE_TEST_APPOINTMENT_FAIL =
  "UPDATE_TEST_APPOINTMENT_FAIL";

