/* TEST APPOINTMENTtS */
export const GET_TEST_APPOINTMENTS = "GET_TEST_APPOINTMENTS";
export const GET_TEST_APPOINTMENTS_SUCCESS =
  "GET_TEST_APPOINTMENTS_SUCCESS";
export const GET_TEST_APPOINTMENTS_FAIL = "GET_TEST_APPOINTMENTS_FAIL";

export const UPDATE_TEST_APPOINTMENT = "UPDATE_TEST_APPOINTMENT";
export const UPDATE_TEST_APPOINTMENT_SUCCESS =
  "UPDATE_TEST_APPOINTMENT_SUCCESS";
export const UPDATE_TEST_APPOINTMENT_FAIL =
  "UPDATE_TEST_APPOINTMENT_FAIL";

