/*  PATIENT TEST APPOINTMENTtS */

export const GET_PATIENT_TEST_APPOINTMENTS_COMPLETED_LIST = "GET_PATIENT_TEST_APPOINTMENTS_COMPLETED_LIST";
export const GET_PATIENT_TEST_APPOINTMENTS_COMPLETED_LIST_SUCCESS =
  "GET_PATIENT_TEST_APPOINTMENTS_COMPLETED_LIST_SUCCESS";
export const GET_PATIENT_TEST_APPOINTMENTS_COMPLETED_LIST_FAIL = "GET_PATIENT_TEST_APPOINTMENTS_COMPLETED_LIST_FAIL";


