export const REGISTER_ORGANIZATION = "REGISTER_ORGANIZATION"
export const REGISTER_ORGANIZATION_SUCCESSFUL = "REGISTER_ORGANIZATION_SUCCESSFUL"
export const REGISTER_ORGANIZATION_FAILED = "REGISTER_ORGANIZATION_FAILED"
