//Get the Hiistory of Units
export const GET_HISTORY_LIST_ROUND = "GET_HISTORY_LIST_ROUND";
export const GET_HISTORY_LIST_ROUND_SUCCESS = "GET_HISTORY_LIST_ROUND_SUCCESS";
export const GET_HISTORY_LIST_ROUND_FAIL = "GET_HISTORY_LIST_ROUND_FAIL";

export const GET_RESULT_HISTORY = "GET_RESULT_HISTORY";
export const GET_RESULT_HISTORY_SUCCESS = "GET_RESULT_HISTORY_SUCCESS";
export const GET_RESULT_HISTORY_FAIL = "GET_RESULT_HISTORY_FAIL";