/* PATHOLOGISTS */
export const GET_ACTIVITY_LOG_FINANCE = "GET_ACTIVITY_LOG_FINANCE";
export const GET_ACTIVITY_LOG_FINANCE_SUCCESS = "GET_ACTIVITY_LOG_FINANCE_SUCCESS";
export const GET_ACTIVITY_LOG_FINANCE_FAIL = "GET_ACTIVITY_LOG_FINANCE_FAIL";

